In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [38]:
#this is new variables for our brain
b_volume=25
femur=295
O_bulb=8
Cere_brum=38
O_lobes=29
Cere_bellum=13

In [39]:
#this is our body mass for OUR brain
ourbrain= O_bulb+ Cere_brum+ O_lobes+ Cere_bellum
print(ourbrain)
mass=10**(3.1854*np.log10(femur)-3.184)/1000
print(mass)

88
48.23597370021272

In [56]:
#find the brain to body mass
brain_body= b_volume/(mass*1000)
#find the cerebrum to brain ratio
cereb_brain= Cere_brum/ourbrain

In [5]:
print(brain_body)
print(cereb_brain)

0.0005182853808523773
0.4318181818181818

In [6]:
df= pd.read_csv("bird_dino_data.csv")

In [7]:
df.head(25)

,Species ID,Bird vs Dino,Body Mass (kg),Olfactory bulbs (cm3),Cerebrum (cm3),Optic Lobes (cm3),Cerebellum (cm3),Brain Stem (cm3)
0,1,B,0.02,0.009,1.53,0.20,0.16,0.06
1,2,B,1.26,0.006,16.81,2.84,1.70,0.68
2,3,B,2.18,0.026,11.08,1.95,0.89,1.15
3,4,D,0.25,0.050,0.41,0.16,0.09,0.12
4,5,B,0.01,0.003,1.57,0.20,0.34,0.08
5,6,D,85.96,0.569,9.52,3.60,5.16,3.78
6,7,D,0.50,0.077,0.60,0.36,0.24,0.17
7,8,B,0.90,0.234,5.95,0.99,0.96,0.55
8,9,B,0.26,0.027,8.36,1.40,1.63,0.86
9,10,D,12.61,0.028,3.71,1.31,1.60,2.17
10,11,B,0.17,0.015,6.09,0.88,1.62,0.49
11,12,B,0.43,0.206,9.45,1.44,2.40,0.85
12,13,B,0.05,0.008,1.63,0.41,0.26,0.17
13,14,B,59.30,0.274,36.85,7.61,6.45,5.13
14,15,D,49.30,1.080,14.81,4.75,3.16,2.35
15,16,B,0.10,0.003,0.63,0.27,0.13,0.07
16,17,B,0.30,0.041,5.50,1.62,1.94,0.77
17,18,B,0.03,0.010,2.22,0.73,0.76,0.29
18,19,B,0.01,0.006,0.46,0.24,0.11,0.06
19,20,D,15.95,0.042,1.61,0.70,0.31,0.40
20,21,B,2.33,0.009,8.05,1.07,1.62,0.68
21,22,D,0.92,0.021,1.38,0.87,0.50,0.33
22,23,B,0.17,0.055,4.69,0.95,0.53,0.53
23,24,B,1.20,0.036,5.18,0.90,1.00,0.58
24,25,B,2.06,0.032,12.24,2.16,2.18,1.07

In [57]:
#make a new column for the whole brain ratio
df["Whole brain"]= df["Olfactory bulbs (cm3)"]
+ df["Cerebrum (cm3)"]+ df["Optic Lobes (cm3)"]+ df["Cerebellum (cm3)"]
df.head()

,Species ID,Bird vs Dino,Body Mass (kg),Olfactory bulbs (cm3),Cerebrum (cm3),Optic Lobes (cm3),Cerebellum (cm3),Brain Stem (cm3),Whole brain,Brain to Body Mass,Cerebrum to Brain
0,1,B,0.02,0.009,1.53,0.20,0.16,0.06,0.009,0.094950,0.805687
1,2,B,1.26,0.006,16.81,2.84,1.70,0.68,0.006,0.016949,0.787132
2,3,B,2.18,0.026,11.08,1.95,0.89,1.15,0.026,0.006397,0.794493
3,4,D,0.25,0.050,0.41,0.16,0.09,0.12,0.050,0.002840,0.577465
4,5,B,0.01,0.003,1.57,0.20,0.34,0.08,0.003,0.211300,0.743019

In [9]:
#find average brain/body mass and cerebrum/whole body for your brain and find averagebrain/body mass and 
#cerebrum/whole  body for birds vs. non-avian birds
brain=df["Whole brain"]
body=df["Body Mass (kg)"]
df["Brain to Body Mass"]=brain/(body*1000)
df.head()

,Species ID,Bird vs Dino,Body Mass (kg),Olfactory bulbs (cm3),Cerebrum (cm3),Optic Lobes (cm3),Cerebellum (cm3),Brain Stem (cm3),Whole brain,Brain to Body Mass
0,1,B,0.02,0.009,1.53,0.20,0.16,0.06,1.899,0.094950
1,2,B,1.26,0.006,16.81,2.84,1.70,0.68,21.356,0.016949
2,3,B,2.18,0.026,11.08,1.95,0.89,1.15,13.946,0.006397
3,4,D,0.25,0.050,0.41,0.16,0.09,0.12,0.710,0.002840
4,5,B,0.01,0.003,1.57,0.20,0.34,0.08,2.113,0.211300

In [10]:
cerebrum=df["Cerebrum (cm3)"]
df["Cerebrum to Brain"]= cerebrum/brain
df.head()

,Species ID,Bird vs Dino,Body Mass (kg),Olfactory bulbs (cm3),Cerebrum (cm3),Optic Lobes (cm3),Cerebellum (cm3),Brain Stem (cm3),Whole brain,Brain to Body Mass,Cerebrum to Brain
0,1,B,0.02,0.009,1.53,0.20,0.16,0.06,1.899,0.094950,0.805687
1,2,B,1.26,0.006,16.81,2.84,1.70,0.68,21.356,0.016949,0.787132
2,3,B,2.18,0.026,11.08,1.95,0.89,1.15,13.946,0.006397,0.794493
3,4,D,0.25,0.050,0.41,0.16,0.09,0.12,0.710,0.002840,0.577465
4,5,B,0.01,0.003,1.57,0.20,0.34,0.08,2.113,0.211300,0.743019

In [11]:
#find the average of each
df_B=df.loc[df["Bird vs Dino"]=="B"]
df_B.head()

,Species ID,Bird vs Dino,Body Mass (kg),Olfactory bulbs (cm3),Cerebrum (cm3),Optic Lobes (cm3),Cerebellum (cm3),Brain Stem (cm3),Whole brain,Brain to Body Mass,Cerebrum to Brain
0,1,B,0.02,0.009,1.53,0.20,0.16,0.06,1.899,0.094950,0.805687
1,2,B,1.26,0.006,16.81,2.84,1.70,0.68,21.356,0.016949,0.787132
2,3,B,2.18,0.026,11.08,1.95,0.89,1.15,13.946,0.006397,0.794493
4,5,B,0.01,0.003,1.57,0.20,0.34,0.08,2.113,0.211300,0.743019
7,8,B,0.90,0.234,5.95,0.99,0.96,0.55,8.134,0.009038,0.731497

In [12]:
df_B.mean()

Species ID               13.388889
Body Mass (kg)            3.932222
Olfactory bulbs (cm3)     0.055556
Cerebrum (cm3)            7.682778
Optic Lobes (cm3)         1.436667
Cerebellum (cm3)          1.371111
Brain Stem (cm3)          0.781667
Whole brain              10.546111
Brain to Body Mass        0.045170
Cerebrum to Brain         0.709443
dtype: float64

In [13]:
cb_bird= df_B["Cerebrum to Brain"].mean()
print(cb_bird)
bb_bird= df_B["Brain to Body Mass"].mean()
print(bb_bird)

0.7094430277327214
0.045170238698633944

In [14]:
df_D=df.loc[df["Bird vs Dino"]=="D"]
df_D.head()

,Species ID,Bird vs Dino,Body Mass (kg),Olfactory bulbs (cm3),Cerebrum (cm3),Optic Lobes (cm3),Cerebellum (cm3),Brain Stem (cm3),Whole brain,Brain to Body Mass,Cerebrum to Brain
3,4,D,0.25,0.050,0.41,0.16,0.09,0.12,0.710,0.002840,0.577465
5,6,D,85.96,0.569,9.52,3.60,5.16,3.78,18.849,0.000219,0.505067
6,7,D,0.50,0.077,0.60,0.36,0.24,0.17,1.277,0.002554,0.469851
9,10,D,12.61,0.028,3.71,1.31,1.60,2.17,6.648,0.000527,0.558063
14,15,D,49.30,1.080,14.81,4.75,3.16,2.35,23.800,0.000483,0.622269

In [15]:
df_D.mean()

Species ID               12.000000
Body Mass (kg)           23.641429
Olfactory bulbs (cm3)     0.266714
Cerebrum (cm3)            4.577143
Optic Lobes (cm3)         1.678571
Cerebellum (cm3)          1.580000
Brain Stem (cm3)          1.331429
Whole brain               8.102429
Brain to Body Mass        0.001400
Cerebrum to Brain         0.547934
dtype: float64

In [16]:
cb_dino=df_D["Cerebrum to Brain"].mean()
print(cb_dino)
bb_dino=df_D["Brain to Body Mass"].mean()
print(bb_dino)

0.5479339483969496
0.0014002983908859297

In [49]:
#measurements, reference data set info about birds + non avian Dino brains
#REACH GOAL: make a function that uses femur length, brain volume, cerebrum width, whole brain width
#return: bird! or non avian Dino  
Cere_brum=38
ourbrain=88
def cerebrumcheck(cerebrum,wholebrain):
    cereb_brain= Cere_brum/ourbrain
    cb_dino=df_D["Cerebrum to Brain"].mean()
    cb_bird=df_B["Cerebrum to Brain"].mean()
    if abs(cereb_brain-cb_dino)> abs(cereb_brain-cb_bird):
        word_f = "Bird!"
    elif abs(cereb_brain-cb_bird)> abs(cereb_brain-cb_dino):
        word_f ="Non Avian Dino"
    return word_f

In [50]:
print(cerebrumcheck(Cere_brum,ourbrain))

Non Avian Dino

In [54]:
def braincheck(cerebrum,wholebrain):
    cereb_brain=Cere_brum/ourbrain
    if abs(brain_body-bb_dino)> abs(brain_body-bb_bird):
        word_f="Bird!"
    elif abs(brain_body-bb_bird)> abs(brain_body-bb_dino):
        word_f="Non Avian Dino"
    return word_f

In [55]:
print(braincheck(Cere_brum,ourbrain))

Non Avian Dino